// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ir/table/inference/disk.proto

package pb_ir_table_inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskRecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Encoded image bytes (JPEG or PNG).
	Image         []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskRecognizeRequest) Reset() {
	*x = DiskRecognizeRequest{}
	mi := &file_ir_table_inference_disk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskRecognizeRequest) ProtoMessage() {}

func (x *DiskRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ir_table_inference_disk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskRecognizeRequest.ProtoReflect.Descriptor instead.
func (*DiskRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_ir_table_inference_disk_proto_rawDescGZIP(), []int{0}
}

func (x *DiskRecognizeRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type DiskRecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Disk                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskRecognizeResponse) Reset() {
	*x = DiskRecognizeResponse{}
	mi := &file_ir_table_inference_disk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskRecognizeResponse) ProtoMessage() {}

func (x *DiskRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ir_table_inference_disk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskRecognizeResponse.ProtoReflect.Descriptor instead.
func (*DiskRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_ir_table_inference_disk_proto_rawDescGZIP(), []int{1}
}

func (x *DiskRecognizeResponse) GetItems() []*Disk {
	if x != nil {
		return x.Items
	}
	return nil
}

type Disk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bounding box in pixels, origin at the top-left corner of the image.
	X      int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width  int32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// Confidence in [0, 1].
	Confidence    float32 `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_ir_table_inference_disk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_ir_table_inference_disk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_ir_table_inference_disk_proto_rawDescGZIP(), []int{2}
}

func (x *Disk) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Disk) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Disk) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Disk) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Disk) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_ir_table_inference_disk_proto protoreflect.FileDescriptor

const file_ir_table_inference_disk_proto_rawDesc = "" +
	"\n" +
	"\x1dir/table/inference/disk.proto\x12\x15pb.ir.table.inference\",\n" +
	"\x14DiskRecognizeRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"J\n" +
	"\x15DiskRecognizeResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.pb.ir.table.inference.DiskR\x05items\"p\n" +
	"\x04Disk\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence2u\n" +
	"\vDiskService\x12f\n" +
	"\tRecognize\x12+.pb.ir.table.inference.DiskRecognizeRequest\x1a,.pb.ir.table.inference.DiskRecognizeResponseB\x19Z\x17./pb_ir_table_inferenceb\x06proto3"

var (
	file_ir_table_inference_disk_proto_rawDescOnce sync.Once
	file_ir_table_inference_disk_proto_rawDescData []byte
)

func file_ir_table_inference_disk_proto_rawDescGZIP() []byte {
	file_ir_table_inference_disk_proto_rawDescOnce.Do(func() {
		file_ir_table_inference_disk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ir_table_inference_disk_proto_rawDesc), len(file_ir_table_inference_disk_proto_rawDesc)))
	})
	return file_ir_table_inference_disk_proto_rawDescData
}

var file_ir_table_inference_disk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ir_table_inference_disk_proto_goTypes = []any{
	(*DiskRecognizeRequest)(nil),  // 0: pb.ir.table.inference.DiskRecognizeRequest
	(*DiskRecognizeResponse)(nil), // 1: pb.ir.table.inference.DiskRecognizeResponse
	(*Disk)(nil),                  // 2: pb.ir.table.inference.Disk
}
var file_ir_table_inference_disk_proto_depIdxs = []int32{
	2, // 0: pb.ir.table.inference.DiskRecognizeResponse.items:type_name -> pb.ir.table.inference.Disk
	0, // 1: pb.ir.table.inference.DiskService.Recognize:input_type -> pb.ir.table.inference.DiskRecognizeRequest
	1, // 2: pb.ir.table.inference.DiskService.Recognize:output_type -> pb.ir.table.inference.DiskRecognizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ir_table_inference_disk_proto_init() }
func file_ir_table_inference_disk_proto_init() {
	if File_ir_table_inference_disk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ir_table_inference_disk_proto_rawDesc), len(file_ir_table_inference_disk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ir_table_inference_disk_proto_goTypes,
		DependencyIndexes: file_ir_table_inference_disk_proto_depIdxs,
		MessageInfos:      file_ir_table_inference_disk_proto_msgTypes,
	}.Build()
	File_ir_table_inference_disk_proto = out.File
	file_ir_table_inference_disk_proto_goTypes = nil
	file_ir_table_inference_disk_proto_depIdxs = nil
}
